classroom.yml

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -38,10 +38,6 @@ jobs:
             echo "HTML tag <title> not found"
             exit 1
           fi
-          if ! grep -q '<body' index.html; then
-            echo "HTML tag <body> not found"
-            exit 1
-          fi
           if ! grep -q '<header' index.html; then
             echo "HTML tag <header> not found"
             exit 1
@@ -54,8 +50,20 @@ jobs:
             echo "HTML tag <p> not found"
             exit 1
           fi
-          if ! grep -q '<footer' index.html; then
-            echo "HTML tag <footer> not found"
+          if ! grep -q '<form' index.html; then
+            echo "HTML tag <form> not found"
+            exit 1
+          fi
+          if ! grep -q '<table' index.html; then
+            echo "HTML tag <table> not found"
+            exit 1
+          fi
+          if ! grep -q '<img' index.html; then
+            echo "HTML tag <img> not found"
+            exit 1
+          fi
+          if ! grep -q '<a ' index.html; then
+            echo "HTML tag <a> not found"
             exit 1
           fi
           echo "HTML structure test passed"
